<?php include PATH_TPL."/tpl.header.phtml"?>
<link href="/css/style.css" type="text/css" rel="stylesheet" />

<div class="container">
  <div class="sidebar1">
    <ul class="nav">
      <li><a href="/manage_center/">进入后台</a></li>
    </ul>
    <p style="height:500px"></p>
  </div>
  <div class="content">
  	<h1><?php echo $blog->subject?></h1>
  	<h4>查看：<?php echo $blog->view?>　评论：<?php echo $blog->comment?>　时间：<?php echo date('Y.m.d H:i', $blog->created)?></h4>
  	<p><?php echo $blog->content?></p>
  	<form method="post" style="padding:15px" action="/blog/commentsave/id/<?php echo $blog->id?>">
  		评论：<br />
			<textarea id="content" name="content"></textarea><br />
			<input type="submit" value="评论"/>
  	</form>
  	<?php foreach ($comment as $v1){?>
  	<p><strong><?php echo $v1['content']?></strong><br /><?php echo date('Y.m.d H:i', $v1['created'])?></p>
  	<?php }?>
  </div>
 </div>
</body>
</html>

<?php include PATH_TPL."/tpl.footer.phtml"?>